# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          npm ci
          npm --prefix functions ci
      - name: Build
        run: |
          npm run build
          npm run build --prefix ./functions
      - name: Test
        run: npm run test -- --watch=false --browsers=ChromeHeadless
      - name: Archive Production Artifact Dist
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
      - name: Archive Production Artifact Lib
        uses: actions/upload-artifact@master
        with:
          name: lib
          path: functions/lib
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact Dist
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Download Artifact Dist
        uses: actions/download-artifact@master
        with:
          name: dist
          path: functions/dist
      - name: Download Artifact Lib
        uses: actions/download-artifact@master
        with:
          name: lib
          path: functions/lib
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
